// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPAG.Data;

#nullable disable

namespace SPAG.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SPAG.Models.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FkUser")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FkUser");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FkUser = 1,
                            Score = 111
                        },
                        new
                        {
                            Id = 2,
                            FkUser = 2,
                            Score = 250
                        },
                        new
                        {
                            Id = 3,
                            FkUser = 3,
                            Score = 2500
                        });
                });

            modelBuilder.Entity("SPAG.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GamerTag")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Hej hallå",
                            GamerTag = "KillerMike",
                            Password = "12345",
                            UserName = "Mike123"
                        },
                        new
                        {
                            Id = 2,
                            GamerTag = "RobustRobert",
                            Password = "12345",
                            UserName = "Robban123"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Im best",
                            GamerTag = "EliteIlyas",
                            Password = "12345",
                            UserName = "Ilyas"
                        });
                });

            modelBuilder.Entity("SPAG.Models.GameModel", b =>
                {
                    b.HasOne("SPAG.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("FkUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
